### ISSUE TITLE
Why '-table' suffix on comment but not on other tables?

### ISSUE THREAD

**Issue by jacekschae** [furkan3ayraktar/clojure-polylith-realworld-example-app#1]
_Question_

In the `clojure.realworld.database.schema` you define [`comment-table`](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/blob/b4c64d7e85d2ec7b5a49e736f70f476f9230e9c1/components/database/src/clojure/realworld/database/schema.clj#L53) and all other tables don't have the `-table` suffix. Is there a reason for that? Most probably I have limited view on this and trying to figure out what is the rationale here.

Thanks for creating this!

**Comment by furkan3ayraktar** [comment]
Thanks for pointing it out. 

I was trying several things from the beginning so this must be a leftover. I don't remember any specific reason to not just use `comment`. I'll fix it right away.

**Comment by furkan3ayraktar** [comment]
Ah I remembered when I checked. [comment](https://clojuredocs.org/clojure.core/comment) is a function from Clojure's core library. I used comment-table in order to not conflict with it.

**Comment by jacekschae** [comment]
Of coures! Now when you mention this it all makes sense. More or less going through it line by line. I'm more of a front-end guy, at least when it comes to Clojure. I appreciate so much the work you put into Polylith. If I find some other things I'll probably bug you again.

**Comment by furkan3ayraktar** [comment]
Perfect! Keep opening issues for the problems you find. We can make it a perfect example for others by fixing everything.
