### ISSUE TITLE
`lein polylith build` fails on fresh checkout

### ISSUE THREAD

**Issue by dpetranek** [furkan3ayraktar/clojure-polylith-realworld-example-app#10]
I wanted to try to run this application, but when I checked it out I couldn't get it to build. It tosses a large stacktrace while building the systems/realworld-backend (attached below).

`lein -v` reports `Leiningen 2.9.1 on Java 1.8.0_202 OpenJDK 64-Bit Server VM`

[build-stacktrace.txt](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/files/3075006/build-stacktrace.txt)

**Comment by dagron** [comment]
Similar error

Leiningen 2.9.1 on Java 11.0.2 OpenJDK 64-Bit Server VM

[stacktrace.txt](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/files/3106328/stacktrace.txt)

**Comment by furkan3ayraktar** [comment]
Hi @dpetranek and @dagron, thanks for reporting this issue. I've tried to recreate this issue but no luck. Did you figure it out in the end?

Also, it would be nice to know which operating system and which Clojure version you are trying to run it.

**Comment by kivio** [comment]
Update lein-ring to 0.12.5 and it will work. 
https://stackoverflow.com/questions/54948986/i-have-an-error-in-clojure-and-leiningen-command
