### ISSUE TITLE
Is the API for users ok?

### ISSUE THREAD

**Issue by jgomo3** [furkan3ayraktar/clojure-polylith-realworld-example-app#2]
In the picture, the term user is sometime in singular and sometime in plural: Is that Ok?

https://raw.githubusercontent.com/furkan3ayraktar/clojure-polylith-realworld-example-app/develop/.media/readme/02_rest_api.png

**Comment by furkan3ayraktar** [comment]
We implemented the [API specifications](https://github.com/gothinkster/realworld/blob/master/api/README.md) of Realworld and these singular/plural endpoints were in those specifications. You can find out more in [Realworld repository](https://github.com/gothinkster/realworld).
