### ISSUE TITLE
Add  .dir-locals.el

### ISSUE THREAD

**Issue by JAremko** [furkan3ayraktar/clojure-polylith-realworld-example-app#5]
@furkan3ayraktar  Mb this demo project(and lein template) should contain `.dir-locals.el`?  It will reduce friction for Emacsers.

 See https://github.com/tengstrand/lein-polylith/pull/19

**Comment by furkan3ayraktar** [comment]
I haven't worked with Emacs much so maybe it would be nice if you can create a PR here in the example project and on the plugin repo? Or, if you can add it to here I can also create a PR on plugin repo to update the template by looking at what you've done here. What do you think about it? @JAremko

**Comment by PEZ** [comment]
The project is quite vanilla `deps.edn`. There is not much friction there. Jack-in including the `:dev` and `:test` aliases and thing should work. That said, in #75 I do include some REPL settings for Calva, because convenience is nice. 😄
